config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  resources :blogs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
    render html: "hello, world!"
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # GET /blogs
  # GET /blogs.json
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |f| %>

  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label  "タイトル" %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label "内容" %>
    <%= f.text_area :body %>
  </div>

  <%= f.submit yield(:button_text) %>

<% end %>

app/views/blogs/edit.html.erb
<% provide(:button_text, '変 更')%>

<div class="blog_form">

  <div class="blog_back blog_btn">
    <%= link_to '戻る', blogs_path %>
  </div>

  <h1>内容編集</h1>

  <%= render 'form', blog: @blog %>

</div>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<div class="blog_header">

  <h1>BLOG一覧</h1>

  <div class="blog_header_content">
    <!-- ブログヘッダー -->
    <h3>投稿数 <%= @blogs.count %></h3>
    <!-- 新規作成ボタン -->
    <div class="blog_create blog_btn">
      <%= link_to '新規作成', new_blog_path %>
    </div>
  </div>

</div>

<!-- ブログ記事一覧 -->
<div class="blogs">

  <% @blogs.each do |blog| %>

    <li>
      <div class="col-md-10">
        <!-- タイトル・ボディ -->
        <span class="blog_title"><%= blog.title %></span>
        <span class="blog_body"><%= blog.body %></span>
        <span class="blog_date"><%= blog.created_at %></span>
      </div>
      <div class="col-md-2">
        <!-- 詳細ボタン -->
        <div class="blog_show blog_btn">
          <%= link_to "詳 細", blog_path(blog) %>
        </div>
      </div>
    </li>

  <% end %>

</div>

app/views/blogs/new.html.erb
<% provide(:button_text, '登 録') %>

<div class="blog_form">

  <div class="blog_back blog_btn">
    <%= link_to '戻る', blogs_path %>
  </div>

  <h1>新規登録</h1>

  <%= render 'form', blog: @blog %>

</div>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<div class="blog_detail_header">
  <!-- 変更ボタン -->
  <div class="blog_back blog_btn">
    <%= link_to '戻 る', blogs_path %>
  </div>
  <!-- 変更ボタン -->
  <div class="blog_update blog_btn">
    <%= link_to '変 更', edit_blog_path(@blog) %>
  </div>
  <!-- 削除ボタン -->
  <div class="blog_delete blog_btn">
    <%= link_to "削 除", @blog, method: :delete, data: { confirm: "You sure?" } %>
  </div>
</div>

<!-- 詳細画面 -->
<div class="blog_detail">
  <li class="blog_detail_list">
    <!-- タイトル・ボディ -->
    <span class="blog_title"><%= @blog.title %></span>
    <span class="blog_body"><%= @blog.body %></span>
    <span class="blog_date"><%= @blog.created_at %></span>
  </li>
<div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <ul>
    <li><%= link_to image_tag("Twitter.png", alt: "Twitter-Icon"), "#" %></li> 
    <li><%= link_to image_tag("youtube.png", alt: "Twitter-Icon"), "#" %></li> 
  </ul>
  <p>@miniblog 2019</p>
</footer>

app/views/layouts/_header.html.erb
<header style="z-index:1000;">　　<!-- 重なりの順序を数値で指定  -->

  <!-- ロゴ -->
  <div class="logo">
    <%= link_to "MINI BLOG", root_path, id: "logo" %>
  </div>

  <!-- ヘッダーナビゲーション　-->
  <div id="nav-header">
    <nav>
      <ul>
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Blog",   blogs_path %></li>
        <li><%= link_to "About",   '#' %></li>
        <li><%= link_to "help",   '#' %></li>
      </ul>
    </nav>
  </div>
  
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Miniblog2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="normal-area">
  <div class="normal-block">
    <div class="imgR">
      <%= image_tag "top.png" %>
      <h1>ミニブログへようこそ！</h1>
      <p>Railsの「Scaffold」を使えば、サクッと基本機能を実装できます。まずは簡単なミニブログを作って、素敵なWebアプリライフをお過ごしください。</p>
    </div>
  </div>
</div>